name = "hype"
description = "A slightly richer version of hyde"
license = "MIT"
homepage = "https://github.com/etrommer/hype"
min_version = "0.11.0"
demo = "https://zola-hyde.netlify.app"

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
]

[author]
name = "Elias Trommer"
homepage = "etrommer.github.io"

[original]
author =  "mdo"
homepage = "http://markdotto.com/"
repo = "https://www.github.com/mdo/hyde"
